using System.Collections.Immutable;
using System.Text;
using DddCleanArchitecture.SourceGenerators.Infrastructure;
using DddCleanArchitecture.SourceGenerators.NavigationRepository.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DddCleanArchitecture.SourceGenerators.NavigationRepository;

public sealed partial class NavigationRepositorySourceGenerator
{
    private static void Generate(SourceProductionContext context, ImmutableArray<NavigableViewInformation> navigableViewInformation)
    {
        var writer = new SourceCodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine("//     This code was generated by DddCleanArchitecture.SourceGenerators.NavigationRepository.")
            .AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.")
            .AppendLine("// </auto-generated>")
            .AppendLine()
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("using System.Windows.Controls;")
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine()
            .AppendLine("namespace DddCleanArchitecture;")
            .AppendLine()
            .AppendLine("public sealed class NavigationRepository");

        using (writer.CreateScope())
        {
            // Static fields
            writer
                .AppendLine("private readonly Dictionary<Type, object> _registeredView;")
                .AppendLine();

            // Constructors
            writer.AppendLine("public NavigationRepository(IServiceProvider serviceProvider)");
            using (writer.CreateScope())
            {
                writer
                    .AppendLine("_registeredView = new Dictionary<Type, object>()")
                    .AppendLine('{');

                writer.IndentationLevel++;
                foreach (var navigableView in navigableViewInformation)
                {
                    foreach (var view in navigableView.ViewTypesNames)
                    {
                        writer
                            .AppendIndent()
                            .Append("[typeof(")
                            .Append(view)
                            .Append(")] = new ")
                            .Append(view)
                            .AppendLine()
                            .AppendIndent()
                            .Append('{')
                            .AppendLine();

                        writer.IndentationLevel++;
                        writer
                            .AppendIndent()
                            .Append("DataContext = ActivatorUtilities.CreateInstance<")
                            .Append(navigableView.ViewModelTypeName)
                            .Append(">(serviceProvider)");
                        writer.IndentationLevel--;

                        writer
                            .AppendLine()
                            .AppendLine("},");
                    }
                }

                writer.IndentationLevel--;

                writer
                    .AppendLine("};");
            }

            writer
                .AppendLine()
                .AppendLine("/// <summary>")
                .AppendLine("/// Try get the specified view.")
                .AppendLine("/// </summary>")
                .AppendLine("/// <typeparam name=\"TView\">The type of the view needed.</typeparam>")
                .AppendLine("/// <returns>The instance of the needed view</returns>")
                .AppendLine("public TView? TryGetView<TView>()")
                .AppendIndentedLine("where TView : Control");
            using (writer.CreateScope())
            {
                writer.AppendLine("return (TView?)(_registeredView.TryGetValue(typeof(TView), out var view) ? view : default);");
            }
        }

        context.AddSource("NavigationRepository.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
    }
}